export const data_2018 = [
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Training - Course Fees ",
    "Expense Area": "Human Resources ",
    "Supplier Name": "CSL - KPMG LLP ",
    "Transaction number": "100269-155 ",
    "Amount": "£39,130.00",
    "Invoice Description":
      "DFIDs contribution to the Civil Service priority learning - Stepping into Leadership Programme for the period September 2017 - March 2018",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "23/01/2018",
    "Expense Type": "",
    "Expense Area": "Research and Evidence Division ",
    "Supplier Name": "THE POLICY PRACTICE LTD ",
    "Transaction number": "202331-102 ",
    "Amount": "£15,038.70",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "15/01/2018",
    "Expense Type": "Hotels - Accommodation only ",
    "Expense Area": "Top Management Group ",
    "Supplier Name": "Foreign & Commonwealth Office ",
    "Transaction number": "100232-102 ",
    "Amount": "£1,540.67",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "15/01/2018",
    "Expense Type": "Other passenger transport ",
    "Expense Area": "Asia  Caribbean and Overseas Territories ",
    "Supplier Name": "Foreign & Commonwealth Office ",
    "Transaction number": "101601-110 ",
    "Amount": "£1,044.07",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "08/01/2018",
    "Expense Type": "Secure Staff Accommodation ",
    "Expense Area": "Research and Evidence Division ",
    "Supplier Name": "Foreign & Commonwealth Office ",
    "Transaction number": "203874-103 ",
    "Amount": "£12,427.33",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "08/01/2018",
    "Expense Type": "Secure Staff Accommodation ",
    "Expense Area": "Asia  Caribbean and Overseas Territories ",
    "Supplier Name": "Foreign & Commonwealth Office ",
    "Transaction number": "204857-102 ",
    "Amount": "£7,848.84",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "08/01/2018",
    "Expense Type": "Project delivery costs ‚Äì supplier services ",
    "Expense Area": "Business Solutions Division Level ",
    "Supplier Name": "FCO RECOVERIES UNIT ",
    "Transaction number": "200002-229 ",
    "Amount": "£124,381.20",
    "Invoice Description":
      "DFID's contribution to the cross-government Global Telecoms Programme for the period Apri to September 2017",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "17/01/2018",
    "Expense Type": "Contract & Agency Staff ",
    "Expense Area": "Business Solutions Division Level ",
    "Supplier Name": "ALLEGIS GROUP LIMITED ",
    "Transaction number": "200005-138 ",
    "Amount": "£2,250.00",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "17/01/2018",
    "Expense Type": "other information and communication technologies ",
    "Expense Area": "Business Solutions Division Level ",
    "Supplier Name": "Leidos Innovations UK ",
    "Transaction number": "200002-173 ",
    "Amount": "£109,885.52",
    "Invoice Description":
      "Managed Service cost for DFID's Cloud based Electronic Document & Record Management (EDRM) System Vault - October to December 2017 ",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Air fares ",
    "Expense Area": "Finance and Corporate Performance Division ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "100008-104 ",
    "Amount": "£580.41",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Air fares ",
    "Expense Area": "Finance and Corporate Performance Division ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "100008-104 ",
    "Amount": "£668.50",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Air fares ",
    "Expense Area": "Asia  Caribbean and Overseas Territories ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "100011-110 ",
    "Amount": "£1,417.26",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Hotels - Accommodation only ",
    "Expense Area": "East and Central Africa ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "100016-110 ",
    "Amount": "£636.75",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Air fares ",
    "Expense Area": "East and Central Africa ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "100016-110 ",
    "Amount": "£1,948.73",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "31/01/2018",
    "Expense Type": "Conferences  Seminars & Meeting/Event Resource ",
    "Expense Area": "Research and Evidence Division ",
    "Supplier Name": "Reuters Foundation Consultants Ltd ",
    "Transaction number": "203874-106 ",
    "Amount": "£15,655.00",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Air fares ",
    "Expense Area": "Research and Evidence Division ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "100039-108 ",
    "Amount": "£966.04",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Hotels - Accommodation only ",
    "Expense Area": "Research and Evidence Division ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "100039-108 ",
    "Amount": "£524.35",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Air fares ",
    "Expense Area": "Research and Evidence Division ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "100039-110 ",
    "Amount": "£1,029.71",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Air fares ",
    "Expense Area":
      "Conflict  Humanitarian  Security & Stabilisation Division ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "100049-102 ",
    "Amount": "£507.57",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "15/01/2018",
    "Expense Type": "Hotels - Accommodation only ",
    "Expense Area": "East and Central Africa ",
    "Supplier Name": "Foreign & Commonwealth Office ",
    "Transaction number": "101612-101 ",
    "Amount": "£4,028.50",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Hotels - Accommodation only ",
    "Expense Area":
      "Conflict  Humanitarian  Security & Stabilisation Division ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "100049-102 ",
    "Amount": "£600.00",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Air fares ",
    "Expense Area":
      "Conflict  Humanitarian  Security & Stabilisation Division ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "100049-134 ",
    "Amount": "£696.47",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "15/01/2018",
    "Expense Type": "Hotels - Accommodation only ",
    "Expense Area": "East and Central Africa ",
    "Supplier Name": "Foreign & Commonwealth Office ",
    "Transaction number": "101612-101 ",
    "Amount": "£4,028.50",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Air fares ",
    "Expense Area": "West and Southern Africa ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "100068-101 ",
    "Amount": "£698.05",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "22/01/2018",
    "Expense Type": "Telephone Usage & services ",
    "Expense Area": "East and Central Africa ",
    "Supplier Name": "Foreign & Commonwealth Office ",
    "Transaction number": "101635-101 ",
    "Amount": "£647.31",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Hotels - Accommodation only ",
    "Expense Area": "East and Central Africa ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "101635-101 ",
    "Amount": "£679.50",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Air fares ",
    "Expense Area": "East and Central Africa ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "101635-101 ",
    "Amount": "£885.50",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "15/01/2018",
    "Expense Type": "Telephone Usage & services ",
    "Expense Area": "West and Southern Africa ",
    "Supplier Name": "Foreign & Commonwealth Office ",
    "Transaction number": "101637-101 ",
    "Amount": "£1,152.44",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Air fares ",
    "Expense Area": "West and Southern Africa ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "101637-101 ",
    "Amount": "£523.90",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Air fares ",
    "Expense Area": "West and Southern Africa ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "101637-102 ",
    "Amount": "£513.41",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "15/01/2018",
    "Expense Type": "Training - Travel & Subsistence ",
    "Expense Area": "East and Central Africa ",
    "Supplier Name": "Foreign & Commonwealth Office ",
    "Transaction number": "100082-101 ",
    "Amount": "£773.21",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Air fares ",
    "Expense Area": "Policy Division ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "100098-101 ",
    "Amount": "£2,027.31",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2018",
    "Expense Type": "Office Supplies ",
    "Expense Area": "Group Operations ",
    "Supplier Name": " Banner",
    "Transaction number": "100106-101 ",
    "Amount": "£534.34",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2018",
    "Expense Type": "Office Equipment - Purchases ",
    "Expense Area": "Group Operations ",
    "Supplier Name": " Plumbnation Ltd ",
    "Transaction number": "100106-101 ",
    "Amount": "£583.37",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Air fares ",
    "Expense Area": "International Relations Division ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "100111-101 ",
    "Amount": "£766.81",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Hotels - Accommodation only ",
    "Expense Area": "West and Southern Africa ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "101638-101 ",
    "Amount": "£753.50",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Air fares ",
    "Expense Area": "West and Southern Africa ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "101638-101 ",
    "Amount": "£767.72",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Air fares ",
    "Expense Area": "West and Southern Africa ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "101638-101 ",
    "Amount": "£752.17",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "23/01/2018",
    "Expense Type": "Data Network - land lines ",
    "Expense Area": "Business Solutions Division Level ",
    "Supplier Name": "VODAFONE LIMITED ",
    "Transaction number": "200002-185 ",
    "Amount": "£91,235.68",
    "Invoice Description":
      "Rental charge for telecommunication data links (WAN) for offices out with the European Union for November 2017 (1 of 2)",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "23/01/2018",
    "Expense Type": "Data Network - land lines ",
    "Expense Area": "Business Solutions Division Level ",
    "Supplier Name": "VODAFONE LIMITED ",
    "Transaction number": "203329-103 ",
    "Amount": "£91,235.68",
    "Invoice Description":
      "Rental charge for telecommunication data links (WAN) for offices out with the European Union for November 2017 (2 of 2)",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Air fares ",
    "Expense Area": "International Relations Division ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "100111-101 ",
    "Amount": "£766.81",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Air fares ",
    "Expense Area": "Internal Audit ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "100121-101 ",
    "Amount": "£608.51",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Air fares ",
    "Expense Area": "Internal Audit ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "100121-101 ",
    "Amount": "£650.10",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Air fares ",
    "Expense Area": "Internal Audit ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "100121-101 ",
    "Amount": "£738.45",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Air fares ",
    "Expense Area": "Internal Audit ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "100121-101 ",
    "Amount": "£897.42",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Air fares ",
    "Expense Area": "Internal Audit ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "100121-101 ",
    "Amount": "£738.45",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "17/01/2018",
    "Expense Type": "Contract & Agency Staff ",
    "Expense Area": "Business Solutions Division Level ",
    "Supplier Name": "ALLEGIS GROUP LIMITED ",
    "Transaction number": "200005-138 ",
    "Amount": "£1,800.00",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Air fares ",
    "Expense Area": "Internal Audit ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "100121-101 ",
    "Amount": "£608.51",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Air fares ",
    "Expense Area": "Internal Audit ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "100121-101 ",
    "Amount": "£897.42",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Hotels - Accommodation only ",
    "Expense Area": "Economic Development Division ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "100124-101 ",
    "Amount": "£524.66",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Air fares ",
    "Expense Area": "Middle East and North Africa Division ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "100146-101 ",
    "Amount": "£1,013.00",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Air fares ",
    "Expense Area": "Middle East and North Africa Division ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "100146-101 ",
    "Amount": "£1,357.00",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Hotels - Accommodation only ",
    "Expense Area": "Middle East and North Africa Division ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "100146-101 ",
    "Amount": "£772.68",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Air fares ",
    "Expense Area": "Middle East and North Africa Division ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "100146-101 ",
    "Amount": "£825.37",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Air fares ",
    "Expense Area": "Middle East and North Africa Division ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "100146-101 ",
    "Amount": "£616.50",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Air fares ",
    "Expense Area": "Middle East and North Africa Division ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "100146-101 ",
    "Amount": "£1,030.57",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Air fares ",
    "Expense Area": "Middle East and North Africa Division ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "100146-101 ",
    "Amount": "£1,157.57",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Air fares ",
    "Expense Area": "Middle East and North Africa Division ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "100146-101 ",
    "Amount": "£1,282.67",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Air fares ",
    "Expense Area": "Middle East and North Africa Division ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "100146-101 ",
    "Amount": "£1,194.17",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Air fares ",
    "Expense Area": "Middle East and North Africa Division ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "100146-101 ",
    "Amount": "£605.70",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2018",
    "Expense Type": "Hotels - Accommodation only ",
    "Expense Area": "Middle East and North Africa Division ",
    "Supplier Name": "Corporate Travel Provider ",
    "Transaction number": "100146-101 ",
    "Amount": "£575.00",
    "Invoice Description": "",
  },
  
  
];
