export const data_2020 = [
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Staff Travel - Air Fares",
    "Expense Area": "East and Central Africa",
    "Supplier Name": "Corporate Provider",
    "Transaction number": "100016-110",
    "Amount": "£871.05",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "08/01/2020",
    "Expense Type": "FCO shared service charges",
    "Expense Area": "Asia, Caribbean and Overseas Territories",
    "Supplier Name": "Foreign & Commonwealth Office",
    "Transaction number": "100025-104",
    "Amount": "£6,392.21",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "17/01/2020",
    "Expense Type": "FCO shared service charges",
    "Expense Area": "Asia, Caribbean and Overseas Territories",
    "Supplier Name": "Foreign & Commonwealth Office",
    "Transaction number": "100025-104",
    "Amount": "£6,897.70",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Staff Travel - Air Fares",
    "Expense Area": "Research and Evidence Division",
    "Supplier Name": "Corporate Provider",
    "Transaction number": "100039-108",
    "Amount": "£2,135.97",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Staff Travel - Air Fares",
    "Expense Area": "Humanitarian, Security and Migration Division",
    "Supplier Name": "Corporate Provider",
    "Transaction number": "100049-102",
    "Amount": "£587.00",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Staff Travel - Air Fares",
    "Expense Area": "Humanitarian, Security and Migration Division",
    "Supplier Name": "Corporate Provider",
    "Transaction number": "100049-132",
    "Amount": "£659.47",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Hotels - Accommodation only",
    "Expense Area": "Humanitarian, Security and Migration Division",
    "Supplier Name": "Corporate Provider",
    "Transaction number": "100049-141",
    "Amount": "£679.20",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "08/01/2020",
    "Expense Type": "Telephone Usage & services",
    "Expense Area": "West and Southern Africa",
    "Supplier Name": "Foreign & Commonwealth Office",
    "Transaction number": "100068-101",
    "Amount": "£2,481.48",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "17/01/2020",
    "Expense Type": "Hotels - Accommodation only",
    "Expense Area": "Asia, Caribbean and Overseas Territories",
    "Supplier Name": "Foreign & Commonwealth Office",
    "Transaction number": "100084-101",
    "Amount": "£1,472.74",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Hotels - Accommodation only",
    "Expense Area": "Asia, Caribbean and Overseas Territories",
    "Supplier Name": "Corporate Provider",
    "Transaction number": "100084-101",
    "Amount": "£683.70",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Hotels - Accommodation only",
    "Expense Area": "Asia, Caribbean and Overseas Territories",
    "Supplier Name": "Corporate Provider",
    "Transaction number": "100084-101",
    "Amount": "£653.20",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "31/01/2020",
    "Expense Type": "Office Supplies",
    "Expense Area": "Group Operations",
    "Supplier Name": "Banner",
    "Transaction number": "100106-101",
    "Amount": "£674.67",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "08/01/2020",
    "Expense Type": "Hotels - Accommodation only",
    "Expense Area": "Internal Audit",
    "Supplier Name": "Foreign & Commonwealth Office",
    "Transaction number": "100121-101",
    "Amount": "£559.40",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "08/01/2020",
    "Expense Type": "Hotels - Accommodation only",
    "Expense Area": "Internal Audit",
    "Supplier Name": "Foreign & Commonwealth Office",
    "Transaction number": "100121-101",
    "Amount": "£559.40",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "08/01/2020",
    "Expense Type": "Hotels - Accommodation only",
    "Expense Area": "Internal Audit",
    "Supplier Name": "Foreign & Commonwealth Office",
    "Transaction number": "100121-101",
    "Amount": "£559.40",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "08/01/2020",
    "Expense Type": "Hotels - Accommodation only",
    "Expense Area": "Internal Audit",
    "Supplier Name": "Foreign & Commonwealth Office",
    "Transaction number": "100121-101",
    "Amount": "£559.40",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "06/01/2020",
    "Expense Type": "Training - Course Fees",
    "Expense Area": "Internal Audit",
    "Supplier Name": "KBR",
    "Transaction number": "100121-101",
    "Amount": "£515.14",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Hotels - Accommodation only",
    "Expense Area": "Internal Audit",
    "Supplier Name": "Corporate Provider",
    "Transaction number": "100121-101",
    "Amount": "£1,690.70",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Hotels - Accommodation only",
    "Expense Area": "Internal Audit",
    "Supplier Name": "Corporate Provider",
    "Transaction number": "100121-101",
    "Amount": "£1,690.70",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Hotels - Accommodation only",
    "Expense Area": "Internal Audit",
    "Supplier Name": "Corporate Provider",
    "Transaction number": "100121-101",
    "Amount": "£1,690.70",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Staff Travel - Air Fares",
    "Expense Area": "Internal Audit",
    "Supplier Name": "Corporate Provider",
    "Transaction number": "100121-101",
    "Amount": "£833.68",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Staff Travel - Air Fares",
    "Expense Area": "Internal Audit",
    "Supplier Name": "Corporate Provider",
    "Transaction number": "100121-101",
    "Amount": "£851.68",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Staff Travel - Air Fares",
    "Expense Area": "Internal Audit",
    "Supplier Name": "Corporate Provider",
    "Transaction number": "100121-101",
    "Amount": "£912.30",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Staff Travel - Air Fares",
    "Expense Area": "Internal Audit",
    "Supplier Name": "Corporate Provider",
    "Transaction number": "100121-101",
    "Amount": "£912.30",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Staff Travel - Air Fares",
    "Expense Area": "Internal Audit",
    "Supplier Name": "Corporate Provider",
    "Transaction number": "100121-101",
    "Amount": "£912.30",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Hotels - Accommodation only",
    "Expense Area": "Economic Development Division",
    "Supplier Name": "Corporate Provider",
    "Transaction number": "100124-101",
    "Amount": "£685.87",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Hotels - Accommodation only",
    "Expense Area": "Economic Development Division",
    "Supplier Name": "Corporate Provider",
    "Transaction number": "100124-101",
    "Amount": "£1,109.02",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Hotels - Accommodation only",
    "Expense Area": "Economic Development Division",
    "Supplier Name": "Corporate Provider",
    "Transaction number": "100124-101",
    "Amount": "£1,109.02",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "06/01/2020",
    "Expense Type": "Training Providers/Facilitation Services",
    "Expense Area": "Communications Division",
    "Supplier Name": "Adobe",
    "Transaction number": "100138-101",
    "Amount": "£909.60",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "17/01/2020",
    "Expense Type": "Mobile telephones & accessories",
    "Expense Area": "West and Southern Africa",
    "Supplier Name": "Foreign & Commonwealth Office",
    "Transaction number": "100144-101",
    "Amount": "£1,403.13",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "31/01/2020",
    "Expense Type": "Hostile Environment Training",
    "Expense Area": "Middle East and North Africa Division",
    "Supplier Name": "Kellogg Brown & Root Limited (KBR)",
    "Transaction number": "100146-101",
    "Amount": "£683.52",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "31/01/2020",
    "Expense Type": "Staff Travel - Air Fares",
    "Expense Area": "West and Southern Africa",
    "Supplier Name": "Supplier Name withheld",
    "Transaction number": "100152-114",
    "Amount": "£663.50",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "06/01/2020",
    "Expense Type": "Subscriptions",
    "Expense Area": "Communications Division",
    "Supplier Name": "Adobe",
    "Transaction number": "100197-101",
    "Amount": "£708.00",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Staff Travel - Air Fares",
    "Expense Area": "Communications Division",
    "Supplier Name": "Corporate Provider",
    "Transaction number": "100197-101",
    "Amount": "£1,271.37",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Staff Travel - Air Fares",
    "Expense Area": "Communications Division",
    "Supplier Name": "Corporate Provider",
    "Transaction number": "100197-101",
    "Amount": "£1,271.37",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "31/01/2020",
    "Expense Type": "Training - Course Fees",
    "Expense Area": "Finance and Corporate Performance Division",
    "Supplier Name": "BIP Solutions",
    "Transaction number": "100201-101",
    "Amount": "£570.00",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Staff Travel - Air Fares",
    "Expense Area": "Top Management Group",
    "Supplier Name": "Corporate Provider",
    "Transaction number": "100232-102",
    "Amount": "£2,700.17",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Staff Travel - Air Fares",
    "Expense Area": "Top Management Group",
    "Supplier Name": "Corporate Provider",
    "Transaction number": "100232-102",
    "Amount": "£4,043.17",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Staff Travel - Air Fares",
    "Expense Area": "Top Management Group",
    "Supplier Name": "Corporate Provider",
    "Transaction number": "100232-102",
    "Amount": "£4,043.17",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Staff Travel - Air Fares",
    "Expense Area": "Top Management Group",
    "Supplier Name": "Corporate Provider",
    "Transaction number": "100232-104",
    "Amount": "£608.04",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Staff Travel - Air Fares",
    "Expense Area": "Top Management Group",
    "Supplier Name": "Corporate Provider",
    "Transaction number": "100232-106",
    "Amount": "£2,194.71",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Staff Travel - Air Fares",
    "Expense Area": "Top Management Group",
    "Supplier Name": "Corporate Provider",
    "Transaction number": "100232-106",
    "Amount": "£2,194.71",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Staff Travel - Air Fares",
    "Expense Area": "Top Management Group",
    "Supplier Name": "Corporate Provider",
    "Transaction number": "100232-106",
    "Amount": "£2,797.20",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Staff Travel - Air Fares",
    "Expense Area": "Top Management Group",
    "Supplier Name": "Corporate Provider",
    "Transaction number": "100232-106",
    "Amount": "£775.00",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Staff Travel - Air Fares",
    "Expense Area": "International Relations Division",
    "Supplier Name": "Corporate Provider",
    "Transaction number": "100240-101",
    "Amount": "£953.53",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Staff Travel - Air Fares",
    "Expense Area": "International Relations Division",
    "Supplier Name": "Corporate Provider",
    "Transaction number": "100240-101",
    "Amount": "£953.63",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Staff Travel - Air Fares",
    "Expense Area": "International Relations Division",
    "Supplier Name": "Corporate Provider",
    "Transaction number": "100240-101",
    "Amount": "£912.80",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Hotels - Accommodation only",
    "Expense Area": "Economic Development Division",
    "Supplier Name": "Corporate Provider",
    "Transaction number": "100275-101",
    "Amount": "£518.24",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Staff Travel - Air Fares",
    "Expense Area": "Economic Development Division",
    "Supplier Name": "Corporate Provider",
    "Transaction number": "100275-101",
    "Amount": "£717.43",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Staff Travel - Air Fares",
    "Expense Area": "Asia, Caribbean and Overseas Territories",
    "Supplier Name": "Supplier Name withheld",
    "Transaction number": "101601-110",
    "Amount": "£771.95",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "08/01/2020",
    "Expense Type": "Other passenger transport",
    "Expense Area": "Asia, Caribbean and Overseas Territories",
    "Supplier Name": "Foreign & Commonwealth Office",
    "Transaction number": "101601-110",
    "Amount": "£1,165.41",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Staff Travel - Air Fares",
    "Expense Area": "Asia, Caribbean and Overseas Territories",
    "Supplier Name": "Supplier Name withheld",
    "Transaction number": "101601-110",
    "Amount": "£950.52",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "08/01/2020",
    "Expense Type": "Unanalysed/miscellaneous travel",
    "Expense Area": "Asia, Caribbean and Overseas Territories",
    "Supplier Name": "Foreign & Commonwealth Office",
    "Transaction number": "101601-110",
    "Amount": "£15,206.00",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "20/01/2020",
    "Expense Type": "Other passenger transport",
    "Expense Area": "Asia, Caribbean and Overseas Territories",
    "Supplier Name": "Foreign & Commonwealth Office",
    "Transaction number": "101601-110",
    "Amount": "£1,085.02",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "20/01/2020",
    "Expense Type": "Further Education costs",
    "Expense Area": "Asia, Caribbean and Overseas Territories",
    "Supplier Name": "Foreign & Commonwealth Office",
    "Transaction number": "101601-110",
    "Amount": "£1,483.00",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "20/01/2020",
    "Expense Type": "Unanalysed/miscellaneous travel",
    "Expense Area": "Asia, Caribbean and Overseas Territories",
    "Supplier Name": "Foreign & Commonwealth Office",
    "Transaction number": "101601-110",
    "Amount": "£12,962.00",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "23/01/2020",
    "Expense Type": "Other passenger transport",
    "Expense Area": "Asia, Caribbean and Overseas Territories",
    "Supplier Name": "Foreign & Commonwealth Office",
    "Transaction number": "101601-110",
    "Amount": "£44,417.70",
    "Invoice Description": "Other passenger transport",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "08/01/2020",
    "Expense Type": "Other passenger transport",
    "Expense Area": "Asia, Caribbean and Overseas Territories",
    "Supplier Name": "Foreign & Commonwealth Office",
    "Transaction number": "101601-110",
    "Amount": "£44,417.70",
    "Invoice Description": "Other passenger transport",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "08/01/2020",
    "Expense Type": "Other passenger transport",
    "Expense Area": "Asia, Caribbean and Overseas Territories",
    "Supplier Name": "Foreign & Commonwealth Office",
    "Transaction number": "101601-110",
    "Amount": "£629.97",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Staff Travel - Air Fares",
    "Expense Area": "Asia, Caribbean and Overseas Territories",
    "Supplier Name": "Supplier Name withheld",
    "Transaction number": "101601-110",
    "Amount": "£1,684.40",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Staff Travel - Air Fares",
    "Expense Area": "Asia, Caribbean and Overseas Territories",
    "Supplier Name": "Supplier Name withheld",
    "Transaction number": "101601-110",
    "Amount": "£1,936.80",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Hotels - Accommodation only",
    "Expense Area": "Asia, Caribbean and Overseas Territories",
    "Supplier Name": "Supplier Name withheld",
    "Transaction number": "101601-110",
    "Amount": "£532.95",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Staff Travel - Air Fares",
    "Expense Area": "Asia, Caribbean and Overseas Territories",
    "Supplier Name": "Supplier Name withheld",
    "Transaction number": "101601-110",
    "Amount": "£1,376.58",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Staff Travel - Air Fares",
    "Expense Area": "Asia, Caribbean and Overseas Territories",
    "Supplier Name": "Supplier Name withheld",
    "Transaction number": "101601-110",
    "Amount": "£810.70",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Staff Travel - Air Fares",
    "Expense Area": "Asia, Caribbean and Overseas Territories",
    "Supplier Name": "Supplier Name withheld",
    "Transaction number": "101601-110",
    "Amount": "£604.00",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Staff Travel - Air Fares",
    "Expense Area": "Asia, Caribbean and Overseas Territories",
    "Supplier Name": "Supplier Name withheld",
    "Transaction number": "101601-110",
    "Amount": "£890.20",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2020",
    "Expense Type": "Staff Travel - Air Fares",
    "Expense Area": "Asia, Caribbean and Overseas Territories",
    "Supplier Name": "Corporate Provider",
    "Transaction number": "101603-101",
    "Amount": "£552.30",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "17/01/2020",
    "Expense Type": "Medical/Health Services",
    "Expense Area": "Asia, Caribbean and Overseas Territories",
    "Supplier Name": "Foreign & Commonwealth Office",
    "Transaction number": "101603-101",
    "Amount": "£1,089.48",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "06/01/2020",
    "Expense Type": "Staff Travel - Air Fares",
    "Expense Area": "Asia, Caribbean and Overseas Territories",
    "Supplier Name": "Foreign & Commonwealth Office",
    "Transaction number": "101604-101",
    "Amount": "£777.61",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "23/01/2020",
    "Expense Type": "Staff Travel - Air Fares",
    "Expense Area": "Asia, Caribbean and Overseas Territories",
    "Supplier Name": "Foreign & Commonwealth Office",
    "Transaction number": "101604-101",
    "Amount": "£914.13",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "23/01/2020",
    "Expense Type": "Staff Travel - Air Fares",
    "Expense Area": "Asia, Caribbean and Overseas Territories",
    "Supplier Name": "Foreign & Commonwealth Office",
    "Transaction number": "101604-101",
    "Amount": "£738.42",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "17/01/2020",
    "Expense Type": "Project delivery costs - supplier services",
    "Expense Area": "Asia, Caribbean and Overseas Territories",
    "Supplier Name": "Foreign & Commonwealth Office",
    "Transaction number": "101605-101",
    "Amount": "£545.61",
    "Invoice Description": "",
  },
 
];
