export const data_2019 = [
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "15/01/2019",
    "Expense Type": "Hotels - Accommodation only",
    "Expense Area": "East and Central Africa",
    "Supplier Name": "Foreign & Commonwealth Office",
    "Transaction number": "100016-110",
    "Amount": "£605.24",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "08/01/2019",
    "Expense Type": "Legal costs",
    "Expense Area": "East and Central Africa",
    "Supplier Name": "Foreign & Commonwealth Office",
    "Transaction number": "100016-110",
    "Amount": "£3,332.94",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "08/01/2019",
    "Expense Type": "Legal costs",
    "Expense Area": "East and Central Africa",
    "Supplier Name": "Foreign & Commonwealth Office",
    "Transaction number": "100016-110",
    "Amount": "£1,611.10",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "08/01/2019",
    "Expense Type": "Legal costs",
    "Expense Area": "East and Central Africa",
    "Supplier Name": "Foreign & Commonwealth Office",
    "Transaction number": "100016-110",
    "Amount": "£827.01",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2019",
    "Expense Type": "Hotels - Accommodation only",
    "Expense Area": "East and Central Africa",
    "Supplier Name": "Corporate Travel Provider",
    "Transaction number": "100016-110",
    "Amount": "£1,032.32",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2019",
    "Expense Type": "Hotels - Accommodation only",
    "Expense Area": "Humanitarian, Security and Migration Division",
    "Supplier Name": "Corporate Travel Provider",
    "Transaction number": "100049-102",
    "Amount": "£829.67",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2019",
    "Expense Type": "Air fares",
    "Expense Area": "Humanitarian, Security and Migration Division",
    "Supplier Name": "Corporate Travel Provider",
    "Transaction number": "100049-133",
    "Amount": "£748.66",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2019",
    "Expense Type": "Air fares",
    "Expense Area": "Humanitarian, Security and Migration Division",
    "Supplier Name": "Corporate Travel Provider",
    "Transaction number": "100049-134",
    "Amount": "£761.71",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2019",
    "Expense Type": "Hotels - Accommodation only",
    "Expense Area": "Humanitarian, Security and Migration Division",
    "Supplier Name": "Corporate Travel Provider",
    "Transaction number": "100049-134",
    "Amount": "£1,088.86",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2019",
    "Expense Type": "Hotels - Accommodation only",
    "Expense Area": "Humanitarian, Security and Migration Division",
    "Supplier Name": "Corporate Travel Provider",
    "Transaction number": "100049-134",
    "Amount": "£713.44",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2019",
    "Expense Type": "Air fares",
    "Expense Area": "Humanitarian, Security and Migration Division",
    "Supplier Name": "Corporate Travel Provider",
    "Transaction number": "100049-134",
    "Amount": "£738.71",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2019",
    "Expense Type": "Air fares",
    "Expense Area": "Humanitarian, Security and Migration Division",
    "Supplier Name": "Corporate Travel Provider",
    "Transaction number": "100049-134",
    "Amount": "£789.66",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2019",
    "Expense Type": "Air fares",
    "Expense Area": "Asia, Caribbean and Overseas Territories",
    "Supplier Name": "Corporate Travel Provider",
    "Transaction number": "100084-101",
    "Amount": "£2,717.42",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2019",
    "Expense Type": "Air fares",
    "Expense Area": "Asia, Caribbean and Overseas Territories",
    "Supplier Name": "Corporate Travel Provider",
    "Transaction number": "100084-101",
    "Amount": "£1,623.70",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2019",
    "Expense Type": "Hotels - Accommodation only",
    "Expense Area": "Asia, Caribbean and Overseas Territories",
    "Supplier Name": "Corporate Travel Provider",
    "Transaction number": "100084-101",
    "Amount": "£2,580.81",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "30/01/2019",
    "Expense Type": "Hotels - Accommodation only",
    "Expense Area": "Asia, Caribbean and Overseas Territories",
    "Supplier Name": "Foreign & Commonwealth Office",
    "Transaction number": "100084-101",
    "Amount": "£555.25",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2019",
    "Expense Type": "Air fares",
    "Expense Area": "Policy Division",
    "Supplier Name": "Corporate Travel Provider",
    "Transaction number": "100098-101",
    "Amount": "£667.61",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2019",
    "Expense Type": "Repairs, Maint, Alter - Other Building Costs",
    "Expense Area": "Group Operations",
    "Supplier Name": "The Bike Storage Company",
    "Transaction number": "100106-101",
    "Amount": "£1,040.04",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2019",
    "Expense Type": "Office Supplies",
    "Expense Area": "Group Operations",
    "Supplier Name": "Banner",
    "Transaction number": "100106-101",
    "Amount": "£730.39",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "07/01/2019",
    "Expense Type": "Office Equipment - Purchases",
    "Expense Area": "Group Operations",
    "Supplier Name": "Plastor",
    "Transaction number": "100106-101",
    "Amount": "£768.00",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "07/01/2019",
    "Expense Type": "Office Equipment - Purchases",
    "Expense Area": "Group Operations",
    "Supplier Name": "Plastor",
    "Transaction number": "100106-101",
    "Amount": "£768.00",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2019",
    "Expense Type": "Air fares",
    "Expense Area": "International Relations Division",
    "Supplier Name": "Corporate Travel Provider",
    "Transaction number": "100111-101",
    "Amount": "£629.96",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2019",
    "Expense Type": "Air fares",
    "Expense Area": "International Relations Division",
    "Supplier Name": "Corporate Travel Provider",
    "Transaction number": "100111-101",
    "Amount": "£537.12",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2019",
    "Expense Type": "Air fares",
    "Expense Area": "International Relations Division",
    "Supplier Name": "Corporate Travel Provider",
    "Transaction number": "100111-101",
    "Amount": "£760.82",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2019",
    "Expense Type": "Air fares",
    "Expense Area": "Internal Audit",
    "Supplier Name": "Corporate Travel Provider",
    "Transaction number": "100121-101",
    "Amount": "£978.74",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2019",
    "Expense Type": "Air fares",
    "Expense Area": "Internal Audit",
    "Supplier Name": "Corporate Travel Provider",
    "Transaction number": "100121-101",
    "Amount": "£978.74",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2019",
    "Expense Type": "Air fares",
    "Expense Area": "Internal Audit",
    "Supplier Name": "Corporate Travel Provider",
    "Transaction number": "100121-101",
    "Amount": "£978.74",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2019",
    "Expense Type": "Air fares",
    "Expense Area": "Internal Audit",
    "Supplier Name": "Corporate Travel Provider",
    "Transaction number": "100121-101",
    "Amount": "£924.92",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "07/01/2019",
    "Expense Type": "Hotels - Accommodation only",
    "Expense Area": "Internal Audit",
    "Supplier Name": "Foreign & Commonwealth Office",
    "Transaction number": "100121-101",
    "Amount": "£2,538.09",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2019",
    "Expense Type": "Hotels - Accommodation only",
    "Expense Area": "Economic Development Division",
    "Supplier Name": "Corporate Travel Provider",
    "Transaction number": "100124-101",
    "Amount": "£784.27",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2019",
    "Expense Type": "Air fares",
    "Expense Area": "Economic Development Division",
    "Supplier Name": "Corporate Travel Provider",
    "Transaction number": "100124-101",
    "Amount": "£638.06",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2019",
    "Expense Type": "Hotels - Accommodation only",
    "Expense Area": "Economic Development Division",
    "Supplier Name": "Corporate Travel Provider",
    "Transaction number": "100124-101",
    "Amount": "£934.36",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "03/01/2019",
    "Expense Type": "Air fares",
    "Expense Area": "Economic Development Division",
    "Supplier Name": "Corporate Travel Provider",
    "Transaction number": "100124-101",
    "Amount": "£638.06",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "08/01/2019",
    "Expense Type": "Medical/Health Services",
    "Expense Area": "West and Southern Africa",
    "Supplier Name": "Foreign & Commonwealth Office",
    "Transaction number": "100148-101",
    "Amount": "£1,683.00",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "15/01/2019",
    "Expense Type": "Medical/Health Services",
    "Expense Area": "West and Southern Africa",
    "Supplier Name": "Foreign & Commonwealth Office",
    "Transaction number": "100148-101",
    "Amount": "£1,701.96",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "07/01/2019",
    "Expense Type": "Office Supplies",
    "Expense Area": "Group Operations",
    "Supplier Name": "Banner",
    "Transaction number": "100161-101",
    "Amount": "£533.78",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "25/01/2019",
    "Expense Type": "Subscriptions",
    "Expense Area": "Communications Division",
    "Supplier Name": "Adobe",
    "Transaction number": "100197-101",
    "Amount": "£708.00",
    "Invoice Description": "",
  },
  {
    Department: "DFID",
    Entity: "DFID",
    "Transaction Date": "04/01/2019",
    "Expense Type": "Subscriptions",
    "Expense Area": "Communications Division",
    "Supplier Name": "ADOBE",
    "Transaction number": "100197-101",
    "Amount": "£708.00",
    "Invoice Description": "",
  },
  
  
];
